apiVersion: batch/v1
kind: Job
metadata:
  finalizers:
    - foregroundDeletion
spec:
  backoffLimit: 2
  template:
    spec:
      serviceAccountName: airflow
      restartPolicy: Never
      containers:
        - name: test-long-running-job
          image: python:3.8.6-slim
          imagePullPolicy: Always
          command: [ "bash" ]
          args: [ "-c", "echo 'start' && sleep 600 && echo 'done'" ]
